### ISSUE TITLE
Training error with batch size != 1

### ISSUE THREAD

**Issue by KhanhNgoDuy** [skhu101/SHERF#42]
Hi, I'm trying to run the training code on `ZJU-mocap` dataset. The code works fine with `batch_size=1` (as in `eval` scripts), but got error when `batch_size=4` (as in `train` scripts).

In [this line](https://github.com/skhu101/SHERF/blob/19ad22adae50bc3d508afe2a5bf132d7249304ad/sherf/training/volumetric_rendering/renderer.py#L320), `smpl_query_pts` is unsqueezed so I believe you want `batch_size=1`. 
But then in [this line](https://github.com/skhu101/SHERF/blob/19ad22adae50bc3d508afe2a5bf132d7249304ad/sherf/training/volumetric_rendering/renderer.py#L564), `smpl_pts` has `batch_size=4`, so we expect `query_pts` to also have `batch_size=4`, but it has `batch_size=1` instead.
Am I missing something, or is this a bug?

Below is the full error description, with `query_pts.shape = (1, 1095757, 3)`, `smpl_pts.shape = (4, 6890, 3)`.

> Traceback (most recent call last):
  File "train.py", line 446, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/lch/anaconda3/envs/sherf/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lch/anaconda3/envs/sherf/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lch/anaconda3/envs/sherf/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lch/anaconda3/envs/sherf/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 441, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 101, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train.py", line 52, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/mnt/HDD1/lch/SHERF/training/training_loop.py", line 365, in training_loop
    loss_Gmain_train, img_loss_raw_train, acc_loss_raw_train, ssim_raw_train, lpips_raw_train, loss_Gmain_Dgen = loss.accumulate_gradients(phase=phase.name, input_data=input_data, real_img=real_img, real_c=real_c, gen_z=gen_z, gen_c=gen_c, gain=phase.interval, cur_nimg=cur_nimg, use_sr_module=use_sr_module, recons_loss=recons_loss, rank=rank)
  File "/mnt/HDD1/lch/SHERF/training/loss.py", line 148, in accumulate_gradients
    gen_img, _gen_ws = self.run_G(input_data, gen_z, gen_c, swapping_prob=swapping_prob, neural_rendering_resolution=neural_rendering_resolution, use_sr_module=use_sr_module)
  File "/mnt/HDD1/lch/SHERF/training/loss.py", line 82, in run_G
    gen_output = self.G.synthesis(ws, input_data, c, neural_rendering_resolution=neural_rendering_resolution, use_sr_module=use_sr_module, update_emas=update_emas, noise_mode='none')
  File "/mnt/HDD1/lch/SHERF/training/triplane.py", line 156, in synthesis
    feature_samples, depth_samples, weights_samples = self.renderer(planes, obs_input_img, obs_input_feature, canonical_sp_conv_volume, obs_smpl_vertex_mask, obs_sp_input, self.decoder, ray_origins, 
  File "/home/lch/anaconda3/envs/sherf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/HDD1/lch/SHERF/training/volumetric_rendering/renderer.py", line 327, in forward
    coarse_canonical_pts, coarse_canonical_viewdir = self.coarse_deform_target2c(input_data['params'], input_data['vertices'], input_data['t_params'], smpl_query_pts, smpl_query_viewdir)
  File "/mnt/HDD1/lch/SHERF/training/volumetric_rendering/renderer.py", line 569, in coarse_deform_target2c
    _, vert_ids, _ = knn_points(query_pts.float(), smpl_pts.float(), K=1)
  File "/home/lch/anaconda3/envs/sherf/lib/python3.8/site-packages/pytorch3d/ops/knn.py", line 172, in knn_points
    raise ValueError("pts1 and pts2 must have the same batch dimension.")
ValueError: pts1 and pts2 must have the same batch dimension.

**Comment by oulaxiaoge** [comment]
Hello, I have been trying this project recently, and then the problem you mentioned also appeared.
I printed out the shape of query_pts and smpl_pts and found that their batch_size was different.

I later found out that it was because I had set --gpus to 1 in train_renderpeople_512x512.sh, but didn't change the --batch parameter (I later changed it to 1 to match --gpus).

I hope it will be helpful to you.
